### ISSUE TITLE
Download_AWS_INMET_daily doesn't run because of the column names

### ISSUE THREAD

**Issue by gabrielhintz** [FilgueirasR/BrazilMet#3]
@FilgueirasR,
I'm getting this error:

"Error in make.names(col.names, unique = TRUE) :
invalid multibyte string 3"

When I run the function 'download_AWS_INMET_daily'. Apparently the columns are not named correctly.

May you help me with that?

**Comment by FilgueirasR** [comment]
Hi @gabrielhintz , thanks for bringing this issue to us. Can you tell me what AWS station, and start and end date you are trying to download?

**Comment by gabrielhintz** [comment]
station A803, from 2014 to 2022.

I solved the problem though by updating the function with the documentation available here.

The only issue I'm getting now is that only the first year is being downloaded.

**Comment by FilgueirasR** [comment]
That's great! With regarding the year problem, this function downloads only one year at a time. To download more years, you can apply a "for". In the next version, I will implement this improvement.

**Comment by gabrielhintz** [comment]
Great.

Thank you for your help and for the package.

**Comment by FilgueirasR** [comment]
Thanks a lot for the feedback. I will end the issue.

**Comment by ammaciel** [comment]
> station A803, from 2014 to 2022.
> 
> I solved the problem though by updating the function with the documentation available here.
> 
> The only issue I'm getting now is that only the first year is being downloaded.

Hi @gabrielhintz, how you solved this problem? I'm with the same error.

@FilgueirasR, I'm attempt with the stations A001, A042 and A711. This package is very useful!

```
df <- download_AWS_INMET_daily(station = "A042", start_date = "2022-01-01", end_date = "2022-12-31")
trying URL 'https://portal.inmet.gov.br/uploads/dadoshistoricos/2022.zip'
Content type 'application/zip' length 90362801 bytes (86.2 MB)
==================================================
downloaded 86.2 MB

Error in make.names(col.names, unique = TRUE) : 
  invalid multibyte string 3
```

Could you help?
